name: main
on:
  push:
    branches:
      - master
    paths:
      - 'inspect/**'
      - '.github/workflows/inspect.yaml'

jobs:
  run-inspect-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: run inspect tests 
        run: |
          cd inspect
          go test -v ./...