name: main
on:
  push:
    branches:
      - master
    paths:
      - 'littlegame/**'
      - '.github/workflows/littlegame.yaml'

jobs:
  build-littlegame:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build project and image
        run: |
          cd littlegame
          make build

      - name: create image and push
        run: |
          cd littlegame
          make image
          make push
