name: main
on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-task:
    runs-on: ubuntu-latest
    steps:
      - name: build project and image
        run: |
          cd tasks
          make build
      - name: tests
        run: make tests
      - name: create image and push
        run: |
          make image
          make push
