name: main
on:
  push:
    branches:
      - master

jobs:
  build-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build project and image
        run: |
          cd tasks
          make build

      - name: tests
        run: |
          cd tasks
          make build
          make tests

      - name: create image and push
        run: |
          cd tasks
          make image
          make push
